repos:
-   repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    - id: flake8
      files: ^(ethstaker_deposit|tests)/
      args: [--config, flake8.ini]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
    - id: mypy
      additional_dependencies: 
        - click==8.1.7
        - eth-typing==5.0.0
        - eth-utils==5.0.0
        - pycryptodome==3.20.0
        - py-ecc==7.0.1
        - ssz==0.5.0
      files: ^ethstaker_deposit/
      args: [--config-file, mypy.ini]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
    - id: check-json
      files: ^ethstaker_deposit/intl
